version: '3.7'

services:

  api:
    build:
      context: .
      dockerfile: ./docker/flask.Dockerfile
    env_file: .env
    volumes:
      - '.:/app'
    ports:
      - 5015:5001
    depends_on: 
      - db
    networks:
      - timeline-network

  db:
    build:
      context: .
      dockerfile: ./docker/postgres.Dockerfile
    env_file: .env
    ports:
      - 5435:5432
    networks:
      - timeline-network

  client:
    build:
      dockerfile: ./docker/react.Dockerfile
      context: .
    ports:
      - "3000:3000"
    networks:
      - timeline-network

networks:
  timeline-network:
    external: true
    driver: bridge
