version: '3.7'

services:

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
    ports:
      - 5015:5000
    env_file: .env
    depends_on: 
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile-Postgres
    ports:
      - 5435:5432
    env_file: .env