version: '3.7'

services:

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - './api:/usr/src/app'
    ports:
      - 5015:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/test
    depends_on: 
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile-Postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres