CREATE TABLE CERTAME (
    id_certame SERIAL NOT NULL,
    n_processo VARCHAR(30),
    CONSTRAINT CERTAME_PK PRIMARY KEY (id_certame)
);

CREATE TABLE TIPO_ATO (
    id_tipo SERIAL NOT NULL,
    descricao TEXT,
    CONSTRAINT TIPO_ATO_PK PRIMARY KEY (id_tipo)
);

CREATE TABLE ATOS (
    id_ato SERIAL NOT NULL,
    data_dodf DATE,
    texto TEXT,
    id_certame INT,
    id_tipo INT,
    CONSTRAINT ATOS_PK PRIMARY KEY (id_ato),

    CONSTRAINT ATOS_CERTAME_FK FOREIGN KEY(id_certame)
        REFERENCES CERTAME(id_certame)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,

    CONSTRAINT ATOS_TIPO_ATO_FK FOREIGN KEY(id_tipo)
        REFERENCES TIPO_ATO(id_tipo)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);