# This is a basic workflow to help you get started with Actions

name: API-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - "backend/api/**"
  pull_request:
    branches: [ main ]
    paths:
      - "backend/api/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_API }}
          dockerfile_directory: .backend/api/
          dockerfile_name: flask.Dockerfile
          docker_options: "--no-cache"
          process_type: web
